import type { Product } from "./types";

const now = Date.now();
const h = 3600_000;

export const extraProducts: Product[] = [
  {
    id: "stake",
    slug: "stake-path-lights",
    name: "Stake path lights",
    tagline: "The walk, marked.",
    description:
      "Six solar pathway stakes in bone metal with a warm amber field. Dusk-to-dawn, no wiring. Typical listing sits near $36. Stake is $24.",
    price: 2400,
    compareAt: 3600,
    cost: 520,
    shipCost: 310,
    weightG: 480,
    supplierId: "cj",
    supplierSku: "CJ-STAKE-6",
    processing: "12–24h",
    score: 84,
    status: "live",
    image: "/products/stake.jpg",
    details: ["6-pack solar", "480g", "US warehouse"],
    launchedAt: now - 1 * h,
  },
  {
    id: "sconce",
    slug: "sconce-wall-lights",
    name: "Sconce wall lights",
    tagline: "The brick, finished.",
    description:
      "Two solar wall sconces. Matte black, a low warm wash, no electrician. Typical listing $42. Sconce is $28.",
    price: 2800,
    compareAt: 4200,
    cost: 610,
    shipCost: 320,
    weightG: 520,
    supplierId: "cj",
    supplierSku: "CJ-SCONCE-2",
    processing: "12–24h",
    score: 83,
    status: "live",
    image: "/products/sconce.jpg",
    details: ["2-pack solar", "520g", "US warehouse"],
    launchedAt: now - 1 * h,
  },
  {
    id: "globe",
    slug: "globe-solar-lights",
    name: "Globe solar lights",
    tagline: "Two small moons for the table.",
    description:
      "Two cracked-glass solar globes. Warm amber, table or stake. Typical listing $32. Globe is $22.",
    price: 2200,
    compareAt: 3200,
    cost: 480,
    shipCost: 300,
    weightG: 360,
    supplierId: "cj",
    supplierSku: "CJ-GLOBE-2",
    processing: "12–24h",
    score: 82,
    status: "live",
    image: "/products/globe.jpg",
    details: ["2-pack glass", "360g", "US warehouse"],
    launchedAt: now - 1 * h,
  },
  {
    id: "torch",
    slug: "torch-solar-stakes",
    name: "Torch solar stakes",
    tagline: "The edge of the yard.",
    description:
      "Four solar flicker torches. LED flame, no open fire, no oil. Typical listing $48. Torch is $32.",
    price: 3200,
    compareAt: 4800,
    cost: 740,
    shipCost: 380,
    weightG: 620,
    supplierId: "cj",
    supplierSku: "CJ-TORCH-4",
    processing: "12–24h",
    score: 81,
    status: "live",
    image: "/products/torch.jpg",
    details: ["4-pack LED", "620g", "US warehouse"],
    launchedAt: now - 1 * h,
  },
  {
    id: "puck",
    slug: "puck-deck-lights",
    name: "Puck deck lights",
    tagline: "The boards, dotted.",
    description:
      "Eight solar deck pucks. Warm dots in the wood. Typical listing $28. Puck is $18.",
    price: 1800,
    compareAt: 2800,
    cost: 340,
    shipCost: 260,
    weightG: 280,
    supplierId: "cj",
    supplierSku: "CJ-PUCK-8",
    processing: "12–24h",
    score: 80,
    status: "live",
    image: "/products/puck.jpg",
    details: ["8-pack solar", "280g", "US warehouse"],
    launchedAt: now - 1 * h,
  },
  {
    id: "canopy",
    slug: "canopy-umbrella-light",
    name: "Canopy umbrella light",
    tagline: "The table under the shade.",
    description:
      "A rechargeable LED ring that clips under a patio umbrella. USB-C. Typical listing $34. Canopy is $22.",
    price: 2200,
    compareAt: 3400,
    cost: 450,
    shipCost: 270,
    weightG: 220,
    supplierId: "cj",
    supplierSku: "CJ-CANOPY-R",
    processing: "12–24h",
    score: 82,
    status: "live",
    image: "/products/canopy.jpg",
    details: ["USB-C ring", "220g", "US warehouse"],
    launchedAt: now - 1 * h,
  },
  {
    id: "wick",
    slug: "wick-led-candles",
    name: "Wick LED candles",
    tagline: "The indoor dusk, without wax.",
    description:
      "Three rechargeable LED pillar candles. Warm flicker. Typical listing $36. Wick is $24.",
    price: 2400,
    compareAt: 3600,
    cost: 510,
    shipCost: 280,
    weightG: 340,
    supplierId: "cj",
    supplierSku: "CJ-WICK-3",
    processing: "12–24h",
    score: 83,
    status: "live",
    image: "/products/wick.jpg",
    details: ["3-pack USB-C", "340g", "US warehouse"],
    launchedAt: now - 1 * h,
  },
  {
    id: "well",
    slug: "well-hummingbird-feeder",
    name: "Well hummingbird feeder",
    tagline: "The pergola, visited.",
    description:
      "Clear glass, bone metal cap. A feeder, not a gadget. Typical listing $28. Well is $18.",
    price: 1800,
    compareAt: 2800,
    cost: 380,
    shipCost: 290,
    weightG: 310,
    supplierId: "cj",
    supplierSku: "CJ-WELL-G",
    processing: "12–24h",
    score: 78,
    status: "live",
    image: "/products/well.jpg",
    details: ["Glass, 310g", "US warehouse"],
    launchedAt: now - 1 * h,
  },
  {
    id: "grove",
    slug: "grove-olive-stem",
    name: "Grove olive stem",
    tagline: "Indoor dusk greenery.",
    description:
      "A faux olive stem in a matte ceramic pot. No watering. Typical listing $48. Grove is $32.",
    price: 3200,
    compareAt: 4800,
    cost: 780,
    shipCost: 420,
    weightG: 680,
    supplierId: "cj",
    supplierSku: "CJ-GROVE-OL",
    processing: "12–24h",
    score: 79,
    status: "live",
    image: "/products/grove.jpg",
    details: ["Ceramic pot", "680g", "US warehouse"],
    launchedAt: now - 1 * h,
  },
  {
    id: "loom",
    slug: "loom-table-runner",
    name: "Loom table runner",
    tagline: "The cloth the lantern sits on.",
    description:
      "Bone linen runner for the outdoor table. Typical listing $34. Loom is $22.",
    price: 2200,
    compareAt: 3400,
    cost: 410,
    shipCost: 250,
    weightG: 180,
    supplierId: "cj",
    supplierSku: "CJ-LOOM-R",
    processing: "12–24h",
    score: 80,
    status: "live",
    image: "/products/loom.jpg",
    details: ["Linen, 180g", "US warehouse"],
    launchedAt: now - 1 * h,
  },
  {
    id: "quill",
    slug: "quill-serving-board",
    name: "Quill serving board",
    tagline: "The board the evening is on.",
    description:
      "Pale oak serving board. Typical listing $42. Quill is $28.",
    price: 2800,
    compareAt: 4200,
    cost: 620,
    shipCost: 340,
    weightG: 540,
    supplierId: "cj",
    supplierSku: "CJ-QUILL-B",
    processing: "12–24h",
    score: 77,
    status: "live",
    image: "/products/quill.jpg",
    details: ["Oak, 540g", "US warehouse"],
    launchedAt: now - 1 * h,
  },
  {
    id: "noon",
    slug: "noon-lunch-tote",
    name: "Noon lunch tote",
    tagline: "The 6:40 kitchen, solved.",
    description:
      "Insulated tote in bone canvas, sage stitch. Typical listing $32. Noon is $22.",
    price: 2200,
    compareAt: 3200,
    cost: 540,
    shipCost: 280,
    weightG: 260,
    supplierId: "cj",
    supplierSku: "CJ-NOON-TOTE",
    processing: "12–24h",
    score: 78,
    status: "live",
    image: "/products/noon.jpg",
    details: ["Insulated", "260g", "US warehouse"],
    launchedAt: now - 1 * h,
  },
  {
    id: "ledge",
    slug: "ledge-picnic-table",
    name: "Ledge picnic table",
    tagline: "Two glasses, one evening.",
    description:
      "A folding picnic wine table. Grass, two glasses, Halo beside it. Typical listing $52. Ledge is $34.",
    price: 3400,
    compareAt: 5200,
    cost: 890,
    shipCost: 480,
    weightG: 920,
    supplierId: "cj",
    supplierSku: "CJ-LEDGE-W",
    processing: "12–24h",
    score: 76,
    status: "live",
    image: "/products/ledge.jpg",
    details: ["Folds flat", "920g", "US warehouse"],
    launchedAt: now - 1 * h,
  },
  {
    id: "reed",
    slug: "reed-outdoor-throw",
    name: "Reed outdoor throw",
    tagline: "The chair, after the sun drops.",
    description:
      "A heavy sage throw for the Adirondack. Typical listing $54. Reed is $36.",
    price: 3600,
    compareAt: 5400,
    cost: 860,
    shipCost: 390,
    weightG: 580,
    supplierId: "cj",
    supplierSku: "CJ-REED-TH",
    processing: "12–24h",
    score: 80,
    status: "live",
    image: "/products/reed.jpg",
    details: ["Sage throw", "580g", "US warehouse"],
    launchedAt: now - 1 * h,
  },
  {
    id: "nimbus",
    slug: "nimbus-patio-fan",
    name: "Nimbus patio fan",
    tagline: "The table stays cool.",
    description:
      "Cordless oscillating patio fan. USB-C, quiet. Typical listing $59. Nimbus is $38.",
    price: 3800,
    compareAt: 5900,
    cost: 980,
    shipCost: 360,
    weightG: 640,
    supplierId: "cj",
    supplierSku: "CJ-NIMBUS-F",
    processing: "12–24h",
    score: 81,
    status: "live",
    image: "/products/nimbus.jpg",
    details: ["USB-C cordless", "640g", "US warehouse"],
    launchedAt: now - 1 * h,
  },
];

export const extraMerch: Record<
  string,
  {
    collection: "patio" | "table" | "travel";
    trending?: boolean;
    benefits: string[];
    faq: { q: string; a: string }[];
    relatedIds: string[];
    notes: { name: string; city: string; quote: string }[];
  }
> = {
  stake: {
    collection: "patio",
    trending: true,
    benefits: ["Six solar stakes, warm amber", "Dusk-to-dawn, no wiring", "Priced under a typical listing"],
    faq: [],
    relatedIds: ["sconce", "puck", "halo"],
    notes: [],
  },
  sconce: {
    collection: "patio",
    trending: true,
    benefits: ["Two solar wall sconces", "No electrician", "Pairs with Halo on the table"],
    faq: [],
    relatedIds: ["stake", "filament", "halo"],
    notes: [],
  },
  globe: {
    collection: "patio",
    trending: true,
    benefits: ["Two glass globes, solar", "Table or stake", "Amber, not a party strobe"],
    faq: [],
    relatedIds: ["wick", "ember", "halo"],
    notes: [],
  },
  torch: {
    collection: "patio",
    trending: true,
    benefits: ["Four LED flicker torches", "No open fire, no oil", "The edge of the yard"],
    faq: [
      {
        q: "Is this a real flame?",
        a: "No. A solar LED in a torch body. We do not sell open-flame torches or fuel.",
      },
    ],
    relatedIds: ["ember", "stake", "halo"],
    notes: [],
  },
  puck: {
    collection: "patio",
    trending: true,
    benefits: ["Eight solar deck pucks", "Warm dots in the boards", "No wiring"],
    faq: [],
    relatedIds: ["stake", "canopy", "filament"],
    notes: [],
  },
  canopy: {
    collection: "patio",
    trending: true,
    benefits: ["Clips under a patio umbrella", "USB-C rechargeable", "The table stays lit"],
    faq: [],
    relatedIds: ["halo", "nimbus", "filament"],
    notes: [],
  },
  wick: {
    collection: "patio",
    trending: true,
    benefits: ["Three rechargeable LED candles", "Warm flicker, no wax", "Indoor sibling to Ember"],
    faq: [
      {
        q: "Do these drip?",
        a: "No. They are LED pillars. Charge them. They do not burn wax.",
      },
    ],
    relatedIds: ["ember", "grove", "halo"],
    notes: [],
  },
  well: {
    collection: "patio",
    benefits: ["Clear glass, bone cap", "Hangs from a pergola", "A feeder, not a gadget"],
    faq: [],
    relatedIds: ["filament", "grove", "halo"],
    notes: [],
  },
  grove: {
    collection: "table",
    benefits: ["Faux olive in ceramic", "No watering", "Sits next to Ember"],
    faq: [],
    relatedIds: ["ember", "wick", "loom"],
    notes: [],
  },
  loom: {
    collection: "table",
    benefits: ["Bone linen runner", "The cloth Halo sits on", "Pairs with Quill"],
    faq: [],
    relatedIds: ["quill", "halo", "meadow"],
    notes: [],
  },
  quill: {
    collection: "table",
    benefits: ["Pale oak serving board", "The evening is on it", "Pairs with Loom and Halo"],
    faq: [],
    relatedIds: ["loom", "shore", "halo"],
    notes: [],
  },
  noon: {
    collection: "travel",
    benefits: ["Insulated bone canvas", "Sage stitch", "The 6:40 kitchen, solved"],
    faq: [],
    relatedIds: ["kiln", "shore", "pulse"],
    notes: [],
  },
  ledge: {
    collection: "travel",
    benefits: ["Folds flat", "Two glasses, one evening", "Halo belongs beside it"],
    faq: [],
    relatedIds: ["meadow", "halo", "reed"],
    notes: [],
  },
  reed: {
    collection: "patio",
    benefits: ["Heavy sage throw", "The chair after the sun drops", "Pairs with Halo"],
    faq: [],
    relatedIds: ["halo", "ledge", "meadow"],
    notes: [],
  },
  nimbus: {
    collection: "patio",
    trending: true,
    benefits: ["Cordless oscillating fan", "USB-C, quiet", "The table stays cool"],
    faq: [],
    relatedIds: ["canopy", "halo", "kiln"],
    notes: [],
  },
};

export const extraSeo: Record<string, { title: string; description: string }> = {
  stake: {
    title: "Stake path lights — 6-pack solar | Marlow",
    description: "Six solar pathway stakes, warm amber. Typical listing $36. Stake is $24. Free tracked US shipping.",
  },
  sconce: {
    title: "Sconce wall lights — 2-pack solar | Marlow",
    description: "Two solar wall sconces, no wiring. Typical listing $42. Sconce is $28. Free tracked US shipping.",
  },
  globe: {
    title: "Globe solar lights — 2-pack glass | Marlow",
    description: "Two solar glass globes. Typical listing $32. Globe is $22. Free tracked US shipping.",
  },
  torch: {
    title: "Torch solar stakes — 4-pack LED | Marlow",
    description: "Four solar flicker torches. No open fire. Typical listing $48. Torch is $32. Free tracked US shipping.",
  },
  puck: {
    title: "Puck deck lights — 8-pack solar | Marlow",
    description: "Eight solar deck pucks. Typical listing $28. Puck is $18. Free tracked US shipping.",
  },
  canopy: {
    title: "Canopy umbrella light — USB-C ring | Marlow",
    description: "Rechargeable LED ring for a patio umbrella. Typical listing $34. Canopy is $22. Free tracked US shipping.",
  },
  wick: {
    title: "Wick LED candles — 3-pack rechargeable | Marlow",
    description: "Three rechargeable LED candles. Typical listing $36. Wick is $24. Free tracked US shipping.",
  },
  well: {
    title: "Well hummingbird feeder — glass | Marlow",
    description: "Clear glass hummingbird feeder. Typical listing $28. Well is $18. Free tracked US shipping.",
  },
  grove: {
    title: "Grove olive stem — faux ceramic | Marlow",
    description: "Faux olive in a matte ceramic pot. Typical listing $48. Grove is $32. Free tracked US shipping.",
  },
  loom: {
    title: "Loom table runner — bone linen | Marlow",
    description: "Bone linen table runner. Typical listing $34. Loom is $22. Free tracked US shipping.",
  },
  quill: {
    title: "Quill serving board — pale oak | Marlow",
    description: "Pale oak serving board. Typical listing $42. Quill is $28. Free tracked US shipping.",
  },
  noon: {
    title: "Noon lunch tote — insulated canvas | Marlow",
    description: "Insulated bone canvas lunch tote. Typical listing $32. Noon is $22. Free tracked US shipping.",
  },
  ledge: {
    title: "Ledge picnic table — folding wine table | Marlow",
    description: "Folding picnic wine table. Typical listing $52. Ledge is $34. Free tracked US shipping.",
  },
  reed: {
    title: "Reed outdoor throw — sage | Marlow",
    description: "Heavy sage outdoor throw. Typical listing $54. Reed is $36. Free tracked US shipping.",
  },
  nimbus: {
    title: "Nimbus patio fan — cordless USB-C | Marlow",
    description: "Cordless oscillating patio fan. Typical listing $59. Nimbus is $38. Free tracked US shipping.",
  },
};
