import { extraProducts } from "./line";
import type {
  Agent,
  Campaign,
  Creative,
  Flow,
  HuntCandidate,
  InboxItem,
  LogItem,
  Order,
  Product,
  ReturnCase,
  Supplier,
} from "./types";

const now = Date.now();
const h = 3600_000;

export const STORE = {
  brand: "Marlow",
  tagline: "Light the yard. Keep the night.",
  ops: "Marlow",
};

export const suppliers: Supplier[] = [
  {
    id: "cj",
    name: "CJ US West — Dusk Goods",
    network: "CJ Dropshipping",
    role: "primary",
    rating: 4.8,
    processing: "12–24h",
    shipping: "USPS / YunExpress tracked, 5–9 days US",
    defectPolicy: "Photo proof, full reship or refund in 48h",
    privateLabel: true,
    notes: "US warehouse for Halo, Filament, Kiln, Pulse, Ember, Meadow, Field. Locked after samples.",
  },
  {
    id: "ali",
    name: "Ningbo Patio Lab",
    network: "AliExpress",
    role: "backup",
    rating: 4.6,
    processing: "48–72h",
    shipping: "ePacket / AliChoice, 9–16 days US",
    defectPolicy: "Partial refund on cosmetic; reship on dead-on-arrival",
    privateLabel: true,
    notes: "Backup for Drift + Shore. Sample inbound.",
  },
  {
    id: "zen",
    name: "Zendrop Home & Garden",
    network: "Zendrop",
    role: "sampling",
    rating: 4.4,
    processing: "24–48h",
    shipping: "US 3PL, 4–8 days",
    defectPolicy: "Store credit on first defect, reship after",
    privateLabel: false,
    notes: "Evaluating Vesper oil refills. No lock yet.",
  },
];

export const products: Product[] = [
  {
    id: "halo",
    slug: "halo-lantern",
    name: "Halo lantern",
    tagline: "The light that holds the evening.",
    description:
      "A rechargeable patio lantern with a low, amber field — made for long dusk hours on a table, a step, or a rail. USB-C, eight-hour burn, weather-sealed body. Ships from a US warehouse when you order.",
    price: 3900,
    compareAt: 4900,
    cost: 860,
    shipCost: 340,
    weightG: 420,
    supplierId: "cj",
    supplierSku: "CJ-HALO-2044",
    processing: "12–24h",
    score: 86,
    status: "live",
    image: "/products/halo.jpg",
    details: ["USB-C, 8h burn", "IPX4 sealed", "420g", "US warehouse"],
    launchedAt: now - 11 * 24 * h,
  },
  {
    id: "kit",
    slug: "evening-kit",
    name: "Evening kit",
    tagline: "The table and the pergola.",
    description:
      "Halo lantern plus 10m Filament solar string lights. Bought together they are $62 — $5 under buying them apart. Two boxes from a US warehouse.",
    price: 6200,
    compareAt: 6700,
    cost: 1480,
    shipCost: 630,
    weightG: 730,
    supplierId: "cj",
    supplierSku: "CJ-KIT-HALO-FIL",
    processing: "12–24h",
    score: 90,
    status: "live",
    image: "/products/kit.jpg",
    details: ["Halo + Filament", "Two boxes", "US warehouse"],
    launchedAt: now - 2 * h,
  },
  {
    id: "filament",
    slug: "filament-lights",
    name: "Filament string lights",
    tagline: "A pergola, quietly finished.",
    description:
      "Solar string lights with a bone-white filament. Ten metres, dusk-to-dawn sensor, no outdoor outlet required. The easiest second item in the cart next to Halo.",
    price: 2800,
    cost: 620,
    shipCost: 290,
    weightG: 310,
    supplierId: "cj",
    supplierSku: "CJ-FIL-1180",
    processing: "12–24h",
    score: 81,
    status: "live",
    image: "/products/filament.jpg",
    details: ["10m solar", "Dusk sensor", "310g", "US warehouse"],
    launchedAt: now - 9 * 24 * h,
  },
  {
    id: "drift",
    slug: "drift-dry-bag",
    name: "Drift dry bag",
    tagline: "Keep the night kit dry.",
    description:
      "A 10L roll-top dry bag in matte sage. Lake, boat, unexpected rain.",
    price: 2400,
    cost: 580,
    shipCost: 310,
    weightG: 180,
    supplierId: "ali",
    supplierSku: "ALI-DRIFT-10L",
    processing: "48–72h",
    score: 78,
    status: "live",
    image: "/products/drift.jpg",
    details: ["10L roll-top", "180g", "Welded seams"],
    launchedAt: now - 6 * 24 * h,
  },
  {
    id: "shore",
    slug: "shore-tote",
    name: "Shore picnic tote",
    tagline: "Two people, one evening.",
    description:
      "Insulated, collapsible, bone canvas with sage stitch. Two people, one evening — plates, a bottle, the cloth.",
    price: 4200,
    cost: 910,
    shipCost: 480,
    weightG: 540,
    supplierId: "ali",
    supplierSku: "ALI-SHORE-TOTE",
    processing: "48–72h",
    score: 74,
    status: "testing",
    image: "/products/shore.jpg",
    details: ["Insulated", "Collapses flat", "540g"],
    launchedAt: now - 2 * 24 * h,
  },
  {
    id: "vesper",
    slug: "vesper-oil",
    name: "Vesper patio oil",
    tagline: "A quieter table.",
    description:
      "Amber glass, two-pack patio oil for the Halo tray. The consumable in the line — the thing that comes back.",
    price: 1600,
    cost: 340,
    shipCost: 260,
    weightG: 220,
    supplierId: "zen",
    supplierSku: "ZEN-VESP-2PK",
    processing: "24–48h",
    score: 80,
    status: "live",
    image: "/products/vesper.jpg",
    details: ["Two-pack", "Amber glass", "Repeat buy"],
    launchedAt: now - 4 * 24 * h,
  },
  {
    id: "kiln",
    slug: "kiln-tumbler",
    name: "Kiln tumbler",
    tagline: "The bottle. Not the logo.",
    description:
      "A 32oz insulated sip bottle in bone steel and sage lid. Holds the walk, the desk, the evening. Typical listing sits near $34. Kiln is $24.",
    price: 2400,
    compareAt: 3400,
    cost: 680,
    shipCost: 290,
    weightG: 380,
    supplierId: "cj",
    supplierSku: "CJ-KILN-32",
    processing: "12–24h",
    score: 85,
    status: "live",
    image: "/products/kiln.jpg",
    details: ["32oz insulated", "380g", "US warehouse"],
    launchedAt: now - 18 * h,
  },
  {
    id: "pulse",
    slug: "pulse-blender",
    name: "Pulse blender bottle",
    tagline: "Breakfast in twenty seconds.",
    description:
      "USB-C personal blender, 22oz cup. Twenty seconds on the counter. Typical listing $39. Pulse is $28.",
    price: 2800,
    compareAt: 3900,
    cost: 690,
    shipCost: 310,
    weightG: 380,
    supplierId: "cj",
    supplierSku: "CJ-PULSE-22",
    processing: "12–24h",
    score: 84,
    status: "live",
    image: "/products/pulse.jpg",
    details: ["USB-C, 22oz", "380g", "US warehouse"],
    launchedAt: now - 16 * h,
  },
  {
    id: "meadow",
    slug: "meadow-cloth",
    name: "Meadow picnic cloth",
    tagline: "The grass, made a table.",
    description:
      "Waterproof picnic cloth in bone canvas, sage stitch, folds into itself. Typical listing $36. Meadow is $24.",
    price: 2400,
    compareAt: 3600,
    cost: 540,
    shipCost: 380,
    weightG: 460,
    supplierId: "cj",
    supplierSku: "CJ-MEAD-78",
    processing: "12–24h",
    score: 82,
    status: "live",
    image: "/products/meadow.jpg",
    details: ["Waterproof fold", "460g", "US warehouse"],
    launchedAt: now - 12 * h,
  },
  {
    id: "ember",
    slug: "ember-flame",
    name: "Ember flame lamp",
    tagline: "The indoor dusk.",
    description:
      "LED flame in smoked glass. The indoor sibling to Halo — no heat, no oil, no open fire. Typical listing $48. Ember is $34.",
    price: 3400,
    compareAt: 4800,
    cost: 920,
    shipCost: 350,
    weightG: 440,
    supplierId: "cj",
    supplierSku: "CJ-EMBR-11",
    processing: "12–24h",
    score: 83,
    status: "live",
    image: "/products/ember.jpg",
    details: ["LED flame", "440g", "USB-C"],
    launchedAt: now - 10 * h,
  },
  {
    id: "field",
    slug: "field-glove",
    name: "Field grooming glove",
    tagline: "The couch, after the shed.",
    description:
      "Sage silicone grooming glove. For the couch, after the shed. Typical listing $22. Field is $14.",
    price: 1400,
    compareAt: 2200,
    cost: 220,
    shipCost: 240,
    weightG: 90,
    supplierId: "cj",
    supplierSku: "CJ-FIELD-G",
    processing: "12–24h",
    score: 79,
    status: "live",
    image: "/products/field.jpg",
    details: ["Silicone, right-hand", "90g", "US warehouse"],
    launchedAt: now - 8 * h,
  },
  ...extraProducts,
];

export const hunts: HuntCandidate[] = [
  {
    id: "hunt-halo",
    name: "Halo lantern",
    niche: "Outdoor dusk / patio",
    cost: 860,
    retail: 3900,
    weightG: 420,
    score: 86,
    angle: "Family table at dusk. Light, not a gadget unboxing.",
    why: [
      "August outdoor demand still live through September",
      "Landed under $12 with US warehouse",
      "4.5× retail vs cost before shipping",
      "Low return: simple lamp, no sizing",
    ],
    risks: ["Seasonal fade after first frost", "Copycats on TikTok Shop"],
    launched: true,
    sample: "locked",
    competition: "medium",
    restricted: false,
    marketplace: 4900,
    cjSku: "CJ-HALO-2044",
  },
  {
    id: "hunt-kiln",
    name: "Kiln tumbler",
    niche: "Amazon Home #1 aisle · tumblers",
    cost: 680,
    retail: 2400,
    weightG: 380,
    score: 85,
    angle: "The bottle on teak. No logo to defend.",
    why: [
      "Amazon Home & Kitchen #1 this week is a branded sip tumbler at $36",
      "CJ generic 32oz US warehouse — we do not list Owala or Stanley",
      "Typical unbranded marketplace $34; we sell $24",
      "Sub-400g, 3.5× cost before shipping",
    ],
    risks: ["Saturated bottle aisle", "Must not look like a clone"],
    launched: true,
    sample: "locked",
    competition: "high",
    restricted: false,
    marketplace: 3400,
    cjSku: "CJ-KILN-32",
  },
  {
    id: "hunt-pulse",
    name: "Pulse blender bottle",
    niche: "Amazon personal blenders · CJ #1 2026",
    cost: 690,
    retail: 2800,
    weightG: 380,
    score: 84,
    angle: "Breakfast in twenty seconds. No kitchen.",
    why: [
      "Amazon personal-blender bestseller class (Ninja Blast is $60 — we do not clone it)",
      "CJ portable blender $5–8 cost, US warehouse",
      "Typical generic listing $39; Pulse is $28",
    ],
    risks: ["Blade complaints", "Battery shipping rules"],
    launched: true,
    sample: "locked",
    competition: "high",
    restricted: false,
    marketplace: 3900,
    cjSku: "CJ-PULSE-22",
  },
  {
    id: "hunt-ember",
    name: "Ember flame lamp",
    niche: "Home décor lighting · CJ flame lamps",
    cost: 920,
    retail: 3400,
    weightG: 440,
    score: 83,
    angle: "The indoor dusk. No voiceover.",
    why: [
      "CJ Shopify 2026 list: LED flame lamps convert on video",
      "Indoor sibling to Halo — same table, different room",
      "Typical marketplace $48; Ember is $34",
    ],
    risks: ["Looks cheap if the LED is too blue", "Seasonal Q4 gifting"],
    launched: true,
    sample: "locked",
    competition: "medium",
    restricted: false,
    marketplace: 4800,
    cjSku: "CJ-EMBR-11",
  },
  {
    id: "hunt-meadow",
    name: "Meadow picnic cloth",
    niche: "Amazon patio picnic blankets",
    cost: 540,
    retail: 2400,
    weightG: 460,
    score: 82,
    angle: "The grass, made a table.",
    why: [
      "Amazon patio picnic blankets are on the movers list this week",
      "CJ waterproof fold, US warehouse",
      "Typical listing $36; Meadow is $24",
    ],
    risks: ["Commodity look", "Returns on staining"],
    launched: true,
    sample: "locked",
    competition: "high",
    restricted: false,
    marketplace: 3600,
    cjSku: "CJ-MEAD-78",
  },
  {
    id: "hunt-glove",
    name: "Field grooming glove",
    niche: "Amazon pet grooming lives",
    cost: 220,
    retail: 1400,
    weightG: 90,
    score: 79,
    angle: "The couch, after the shed.",
    why: [
      "Amazon pet-grooming lives are moving",
      "Almost no shipping drag at 90g",
      "Typical listing $22; Field is $14",
    ],
    risks: ["Race-to-bottom pricing", "One-star sizing"],
    launched: true,
    sample: "locked",
    competition: "high",
    restricted: false,
    marketplace: 2200,
    cjSku: "CJ-FIELD-G",
  },
  {
    id: "hunt-lunch",
    name: "Insulated lunch tote",
    niche: "Back to school",
    cost: 540,
    retail: 2200,
    weightG: 260,
    score: 78,
    angle: "The 6:40am kitchen, solved.",
    why: ["August–September spike", "Parent buyers", "Typical marketplace $32; we would sell $22"],
    risks: ["Commodity look", "Needs a tighter brand story"],
    launched: true,
    sample: "locked",
    competition: "high",
    restricted: false,
    marketplace: 3200,
    cjSku: "CJ-NOON-TOTE",
  },
  {
    id: "hunt-chair",
    name: "Fold telescopic chair",
    niche: "Amazon camping chairs #1",
    cost: 1280,
    retail: 3900,
    weightG: 1180,
    score: 68,
    angle: "The second seat at the fire.",
    why: [
      "Amazon camping chairs are #1 in patio furniture this week",
      "CJ April list: telescopic folding chair",
      "Typical marketplace $59",
    ],
    risks: ["Over 1kg — shipping eats the multiple", "Frame-weld returns"],
    launched: false,
    sample: "needed",
    competition: "high",
    restricted: false,
    marketplace: 5900,
    cjSku: "CJ-CHAIR-TEL",
  },
  {
    id: "hunt-aftersun",
    name: "After-sun repair kit",
    niche: "Beauty / late summer",
    cost: 410,
    retail: 2400,
    weightG: 140,
    score: 81,
    angle: "The evening after the lake day.",
    why: ["Consumable", "Tiny ship weight", "~70% gross"],
    risks: ["Ingredient claims", "Short seasonal window"],
    launched: false,
    sample: "needed",
    competition: "medium",
    restricted: true,
    marketplace: 2800,
    cjSku: "CJ-SUN-KIT",
  },
  {
    id: "hunt-mask",
    name: "Red light face mask",
    niche: "At-home wellness",
    cost: 1180,
    retail: 5900,
    weightG: 480,
    score: 71,
    angle: "A ten-minute evening ritual.",
    why: ["High AOV", "Strong before/after creative"],
    risks: ["Claims/compliance", "Higher return rate", "Cost near $12 ceiling"],
    launched: false,
    sample: "needed",
    competition: "medium",
    restricted: true,
    marketplace: 7900,
    cjSku: "CJ-MASK-RL",
  },
];

function step(id: string, type: Flow["steps"][number]["type"], title: string, detail: string) {
  return { id, type, title, detail };
}

export const flows: Flow[] = [
  {
    id: "flow-route",
    name: "Auto-route to supplier",
    description: "Every paid order becomes a PO at the locked supplier. No inventory. No waiting on a human.",
    enabled: true,
    trigger: "Order paid",
    steps: [
      step("t", "trigger", "Order paid", "Storefront or simulated checkout"),
      step("c", "condition", "In stock at supplier", "Skip if SKU marked OOS"),
      step("r", "route", "Create supplier PO", "Send SKU, address, shipping template"),
      step("e", "email", "Order received", "Set expectation: 5–9 day tracked"),
      step("n", "notify", "Ops ping", "Log the PO id in Relay"),
    ],
    fired: 42,
    converted: 42,
    revenue: 0,
  },
  {
    id: "flow-abandon",
    name: "Abandoned cart recovery",
    description: "Three touches: 45 minutes, next evening, day three. Halo as the hero, 10% to close.",
    enabled: true,
    trigger: "Cart idle 45m",
    steps: [
      step("t", "trigger", "Cart idle", "Items in cart, no checkout"),
      step("w1", "wait", "Wait 45 minutes", "Fast-forwarded in the night shift"),
      step("e1", "email", "The table is still set", "Halo image + cart contents"),
      step("w2", "wait", "Wait 22 hours", "Second dusk window"),
      step("d", "discount", "Issue DUSK10", "10% off, 48h"),
      step("e2", "email", "A quieter evening", "Discount in the second note"),
      step("s", "sms", "SMS if opted in", "One line, one link"),
    ],
    fired: 19,
    converted: 6,
    revenue: 18700,
  },
  {
    id: "flow-welcome",
    name: "Welcome series",
    description: "How to place Halo, how to charge it, how Filament hangs. Education, not a blast.",
    enabled: true,
    trigger: "First purchase delivered",
    steps: [
      step("t", "trigger", "Delivered", "Tracking shows delivered"),
      step("e1", "email", "Place it low", "Lantern reads better at table height"),
      step("w", "wait", "Wait 3 days", ""),
      step("e2", "email", "The second light", "Filament as the attach"),
    ],
    fired: 11,
    converted: 3,
    revenue: 8400,
  },
  {
    id: "flow-kill",
    name: "48-hour ad kill",
    description: "If contribution after ads is negative for two simulated days, pause the campaign and flag the SKU.",
    enabled: true,
    trigger: "Campaign age ≥ 48h",
    steps: [
      step("t", "trigger", "Campaign tick", "Night shift P&L rollup"),
      step("c", "condition", "Contribution < 0", "Revenue − COGS − ship − fees − ads"),
      step("p", "pause_ad", "Pause campaign", "Do not wait for a weekly review"),
      step("n", "notify", "Alert ops", "Kill or rewrite the angle"),
    ],
    fired: 2,
    converted: 2,
    revenue: 0,
  },
  {
    id: "flow-review",
    name: "Review request",
    description: "Seven days after delivery, ask for the dusk photo — not a star rating lecture.",
    enabled: true,
    trigger: "7 days post-delivery",
    steps: [
      step("t", "trigger", "Delivered + 7d", ""),
      step("e", "email", "Send a still from the table", "Photo request + 10-word ask"),
    ],
    fired: 8,
    converted: 4,
    revenue: 0,
  },
  {
    id: "flow-vip",
    name: "VIP tag",
    description: "Tag anyone over $80 lifetime. Future drops go to them first.",
    enabled: false,
    trigger: "Lifetime spend ≥ $80",
    steps: [
      step("t", "trigger", "Order paid", ""),
      step("c", "condition", "LTV ≥ $80", ""),
      step("g", "tag", "Tag VIP", "Segment: dusk-circle"),
      step("e", "email", "You’re on the list", "Quiet, not a punch card"),
    ],
    fired: 0,
    converted: 0,
    revenue: 0,
  },
  {
    id: "flow-winback",
    name: "Win-back 30 days",
    description: "One quiet note after a month of silence. No fake scarcity. A table, still set.",
    enabled: true,
    trigger: "No order in 30 days",
    steps: [
      step("t", "trigger", "Idle 30d", "Last delivered order aged out"),
      step("e", "email", "The table is still there", "Halo + Vesper, no countdown"),
    ],
    fired: 3,
    converted: 1,
    revenue: 3900,
  },
];

export const campaigns: Campaign[] = [
  {
    id: "ad-halo-meta",
    name: "Halo · dusk table",
    channel: "Meta",
    productId: "halo",
    dailyBudget: 4800,
    spend: 31200,
    clicks: 1840,
    purchases: 38,
    revenue: 148200,
    status: "active",
    launchedAt: now - 9 * 24 * h,
    angle: "Static of the lantern on teak. Caption: the evening, held.",
    utm: "utm_source=meta&utm_medium=paid&utm_campaign=halo-dusk",
  },
  {
    id: "ad-halo-tt",
    name: "Halo · backyard UGC",
    channel: "TikTok",
    productId: "halo",
    dailyBudget: 3600,
    spend: 21400,
    clicks: 2610,
    purchases: 21,
    revenue: 81900,
    status: "active",
    launchedAt: now - 6 * 24 * h,
    angle: "Phone video, family dinner, cut to the lamp. No voiceover.",
    utm: "utm_source=tiktok&utm_medium=paid&utm_campaign=halo-ugc",
  },
  {
    id: "ad-shore-meta",
    name: "Shore · picnic test",
    channel: "Meta",
    productId: "shore",
    dailyBudget: 2000,
    spend: 4100,
    clicks: 190,
    purchases: 2,
    revenue: 8400,
    status: "active",
    launchedAt: now - 36 * h,
    angle: "Tote in grass. Weak hook — contribution is slipping.",
    utm: "utm_source=meta&utm_medium=paid&utm_campaign=shore-test",
  },
  {
    id: "ad-filament-g",
    name: "Filament · search",
    channel: "Google",
    productId: "filament",
    dailyBudget: 1800,
    spend: 9200,
    clicks: 640,
    purchases: 11,
    revenue: 30800,
    status: "paused",
    launchedAt: now - 8 * 24 * h,
    angle: "Exact match 'solar patio lights'.",
    utm: "utm_source=google&utm_medium=cpc&utm_campaign=filament-search",
  },
  {
    id: "ad-kiln-meta",
    name: "Kiln · sip test",
    channel: "Meta",
    productId: "kiln",
    dailyBudget: 2000,
    spend: 1640,
    clicks: 188,
    purchases: 5,
    revenue: 12000,
    status: "active",
    launchedAt: now - 20 * h,
    angle: "The bottle on teak. No brand unboxing.",
    utm: "utm_source=meta&utm_medium=paid&utm_campaign=kiln-sip",
  },
  {
    id: "ad-pulse-tt",
    name: "Pulse · morning UGC",
    channel: "TikTok",
    productId: "pulse",
    dailyBudget: 2000,
    spend: 880,
    clicks: 310,
    purchases: 2,
    revenue: 5600,
    status: "active",
    launchedAt: now - 14 * h,
    angle: "Twenty seconds. No kitchen.",
    utm: "utm_source=tiktok&utm_medium=paid&utm_campaign=pulse-ugc",
  },
  {
    id: "ad-ember-meta",
    name: "Ember · indoor dusk",
    channel: "Meta",
    productId: "ember",
    dailyBudget: 2000,
    spend: 720,
    clicks: 96,
    purchases: 2,
    revenue: 6800,
    status: "active",
    launchedAt: now - 11 * h,
    angle: "Smoked glass. No voiceover.",
    utm: "utm_source=meta&utm_medium=paid&utm_campaign=ember-dusk",
  },
];

const names = [
  ["Rowan Hale", "Portland, OR", "rowan.h@example.com"],
  ["Sasha Quinn", "Austin, TX", "sasha.q@example.com"],
  ["Eden Park", "Denver, CO", "eden.p@example.com"],
  ["Milo Hart", "Nashville, TN", "milo.h@example.com"],
  ["Ira Bennett", "Seattle, WA", "ira.b@example.com"],
  ["Noor Ellison", "Chicago, IL", "noor.e@example.com"],
  ["Jules Abram", "Brooklyn, NY", "jules.a@example.com"],
];

export const orders: Order[] = [
  {
    id: "o1",
    number: "#M10427",
    createdAt: now - 2 * h,
    customer: names[0][0],
    city: names[0][1],
    email: names[0][2],
    items: [{ productId: "halo", name: "Halo lantern", qty: 1, price: 3900 }],
    status: "routed",
    supplierId: "cj",
    source: "sim",
    campaignId: "ad-halo-meta",
  },
  {
    id: "o2",
    number: "#M10426",
    createdAt: now - 5 * h,
    customer: names[1][0],
    city: names[1][1],
    email: names[1][2],
    items: [
      { productId: "halo", name: "Halo lantern", qty: 1, price: 3900 },
      { productId: "filament", name: "Filament string lights", qty: 1, price: 2800 },
    ],
    status: "processing",
    supplierId: "cj",
    source: "sim",
    campaignId: "ad-halo-tt",
  },
  {
    id: "o3",
    number: "#M10425",
    createdAt: now - 14 * h,
    customer: names[2][0],
    city: names[2][1],
    email: names[2][2],
    items: [{ productId: "drift", name: "Drift dry bag", qty: 1, price: 2400 }],
    status: "shipped",
    supplierId: "ali",
    tracking: "9400 1120 3300 0001",
    source: "sim",
  },
  {
    id: "o4",
    number: "#M10424",
    createdAt: now - 30 * h,
    customer: names[3][0],
    city: names[3][1],
    email: names[3][2],
    items: [{ productId: "halo", name: "Halo lantern", qty: 2, price: 3900 }],
    status: "delivered",
    supplierId: "cj",
    tracking: "9400 1120 3300 0002",
    source: "sim",
    campaignId: "ad-halo-meta",
  },
  {
    id: "o5",
    number: "#M10423",
    createdAt: now - 40 * h,
    customer: names[4][0],
    city: names[4][1],
    email: names[4][2],
    items: [{ productId: "shore", name: "Shore picnic tote", qty: 1, price: 4200 }],
    status: "paid",
    supplierId: "ali",
    source: "sim",
    campaignId: "ad-shore-meta",
  },
  {
    id: "o6",
    number: "#M10422",
    createdAt: now - 52 * h,
    customer: names[5][0],
    city: names[5][1],
    email: names[5][2],
    items: [{ productId: "vesper", name: "Vesper patio oil", qty: 2, price: 1600 }],
    status: "delivered",
    supplierId: "zen",
    source: "sim",
    recovered: true,
  },
];

export const inbox: InboxItem[] = [
  {
    id: "m1",
    at: now - 2 * h,
    channel: "email",
    to: names[0][2],
    subject: "Halo is on its way from the warehouse",
    body: "Rowan — we sent the PO to CJ US West. Tracked shipping usually lands in 5–9 days. Place Halo at table height. It reads better there than on a high shelf.",
    flowId: "flow-route",
  },
  {
    id: "m2",
    at: now - 6 * h,
    channel: "email",
    to: "guest.cart@example.com",
    subject: "The table is still set",
    body: "You left a Halo lantern in the bag. It holds an evening the way a fire does — without the smoke. Still here when you are.",
    flowId: "flow-abandon",
  },
  {
    id: "m3",
    at: now - 31 * h,
    channel: "email",
    to: names[3][2],
    subject: "Place it low",
    body: "Milo — both lanterns delivered. Set them on the table, not the rail. Charge over lunch; they burn through a long dusk.",
    flowId: "flow-welcome",
  },
  {
    id: "m4",
    at: now - 3 * h,
    channel: "ops",
    to: "ops@marlow",
    subject: "Shore · picnic test is underwater",
    body: "Contribution after ads is negative on the Shore tote test. 48-hour kill is armed. Pause or rewrite the hook tonight.",
    flowId: "flow-kill",
  },
];

export const logs: LogItem[] = [
  {
    id: "l1",
    at: now - 2 * h,
    flowId: "flow-route",
    message: "PO CJ-2044-19 created for #M10427 · Halo lantern",
    tone: "ok",
  },
  {
    id: "l2",
    at: now - 3 * h,
    flowId: "flow-kill",
    message: "Shore · picnic test contribution −$18.40 today. Kill armed.",
    tone: "warn",
  },
  {
    id: "l3",
    at: now - 6 * h,
    flowId: "flow-abandon",
    message: "Recovery note sent · cart $39.00",
    tone: "info",
  },
  {
    id: "l4",
    at: now - 5 * h,
    flowId: "flow-route",
    message: "PO CJ-1180-08 created for #M10426 · Halo + Filament",
    tone: "ok",
  },
];

export const sampleCustomers = names;

export const creatives: Creative[] = [
  {
    id: "cr-halo-static",
    campaignId: "ad-halo-meta",
    hook: "The evening, held.",
    format: "static",
    status: "winner",
    spend: 18400,
    purchases: 26,
  },
  {
    id: "cr-halo-teak",
    campaignId: "ad-halo-meta",
    hook: "Lantern on teak. No unboxing.",
    format: "static",
    status: "testing",
    spend: 12800,
    purchases: 12,
  },
  {
    id: "cr-halo-ugc",
    campaignId: "ad-halo-tt",
    hook: "Family dinner. Cut to the lamp. No voiceover.",
    format: "ugc",
    status: "testing",
    spend: 21400,
    purchases: 21,
  },
  {
    id: "cr-shore-grass",
    campaignId: "ad-shore-meta",
    hook: "Tote in grass.",
    format: "static",
    status: "testing",
    spend: 4100,
    purchases: 2,
  },
  {
    id: "cr-fil-search",
    campaignId: "ad-filament-g",
    hook: "solar patio lights — exact",
    format: "search",
    status: "winner",
    spend: 9200,
    purchases: 11,
  },
  {
    id: "cr-kiln-teak",
    campaignId: "ad-kiln-meta",
    hook: "The bottle on teak. No logo.",
    format: "static",
    status: "testing",
    spend: 1640,
    purchases: 5,
  },
  {
    id: "cr-pulse-lemon",
    campaignId: "ad-pulse-tt",
    hook: "Twenty seconds. No kitchen.",
    format: "ugc",
    status: "testing",
    spend: 880,
    purchases: 2,
  },
  {
    id: "cr-ember-glass",
    campaignId: "ad-ember-meta",
    hook: "Smoked glass. The indoor dusk.",
    format: "static",
    status: "testing",
    spend: 720,
    purchases: 2,
  },
];

export const agents: Agent[] = [
  {
    id: "catalog",
    name: "Catalog agent",
    brief: "Scores hunts, flags restricted claims, never lists a SKU without a sample lock.",
    enabled: true,
    lastAction: "Mapped Amazon tumbler #1 to Kiln. Owala not cloned. Five CJ matches live.",
    pending: {
      kind: "request_sample",
      targetId: "hunt-chair",
      title: "Weigh the telescopic chair before a $20 test",
      detail: "Amazon camping chairs are moving. 1180g — shipping may eat the multiple. Do not spend until the unit is on the scale.",
    },
  },
  {
    id: "marketing",
    name: "Marketing agent",
    brief: "Paces budgets, tests hooks, proposes kills. Never buys engagement. Human checkpoint on spend changes.",
    enabled: true,
    lastAction: "Halo dusk table winning. Shore test underwater.",
    pending: {
      kind: "kill_ad",
      targetId: "ad-shore-meta",
      title: "Pause Shore · picnic test",
      detail: "Contribution after COGS, fees, and ads is negative past 36 hours. Rewrite the hook or bury the SKU.",
    },
  },
  {
    id: "fulfillment",
    name: "Fulfillment agent",
    brief: "Routes POs, picks the faster warehouse, opens RMAs with photo proof.",
    enabled: true,
    lastAction: "PO CJ-2044-19 routed in the same breath as capture.",
    pending: null,
  },
  {
    id: "support",
    name: "Support agent",
    brief: "Drafts replies from the policy. Escalates refunds. Does not invent tracking numbers.",
    enabled: false,
    lastAction: "Off — drafts wait for a human.",
    pending: {
      kind: "draft_mail",
      targetId: "o3",
      title: "Draft a delivery note for #M10425",
      detail: "Drift dry bag shipped. Ask to confirm the roll-top arrived sealed. No review begging.",
    },
  },
];

export const returns: ReturnCase[] = [
  {
    id: "r1",
    orderId: "o3",
    number: "#M10425",
    reason: "Cosmetic scuff on the roll-top. Photo attached.",
    status: "open",
    at: now - 8 * h,
  },
];

